name: 'Assets Upload Action'
description: 'Action for upload assets'
author: 'zezaeoh <zezaeoh@github.com>'
inputs:
  source-dir:
    required: true
    description: 'directory to upload'
  destination-dir:
    required: false
    default: /
    description: 'destination directory for upload'
  concurrency:
    required: false
    default: "5"
    description: 'concurrency level'
  bucket:
    required: false
    description: 's3 bucket name to upload'
  skip-files:
    required: false
    description: 'list of skip files'
runs:
  using: 'node16'
  main: 'dist/index.js'
